config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :groups, only: [:index, :show, :new, :create] do
    resources :deals, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated do
    root :to => 'groups#index', as: :authenticated_root
  end
  root "application#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Deal, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups
  before_destroy { groups.clear }

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :deals
  before_destroy { deals.clear }

  validates :name, presence: true
  validates :icon, presence: true

  def expenses
    total = 0
    deals.each { |deal| total += deal.amount }
    total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :deals, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def index; end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :last_name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :last_name, :email, :password, :current_password)
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]
  before_action :set_group, only: %i[new edit create index]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /deals/new
  def new
    @category = params[:category]
    @deal = Deal.new
    @title = 'Transaction'
    @previous_path = group_path(@group)
  end

  # POST /deals or /deals.json
  def create
    @categories = params[:category_ids]
    @deal = @group.deals.create(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to group_path(@group), notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def deal_params
    params.require(:deal).permit(:name, :amount).merge(user_id: current_user.id)
  end

  def group_params
    params.require(:deal).permit(:category_ids)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
    @total = total_expenses(current_user)
    @title = 'Categories'
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @deals = @group.deals.order(created_at: :desc)
    @title = @group.name
    @previous_path = groups_path
  end

  # GET /groups/new
  def new
    @group = Group.new
    @title = 'New Category'
    @previous_path = groups_path
  end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def disp_alerts
    if notice
      render 'layouts/notice'
    elsif alert
      render 'layouts/alert'
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_expenses(user)
    total = 0
    user.deals.each { |deal| total += deal.amount }
    total
  end
end

app/views/application/index.html.erb
<div class="h-80vh d-flex align-items-center justify-content-center">
  <h1 class='fs-1 fw-bold fst-italic'>Bugdery</h1>
</div>
<div class= 'd-flex flex-column'>
  <%= link_to 'LOG IN',new_user_session_path, class: 'btn btn-primary my-2 p-2' %>
  <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn my-2 p-2' %>
</div>

app/views/deals/_deal.html.erb
<div class="m-2 bg-white border d-flex justify-content-between p-2" id="<%= dom_id deal %>">
  <div class="d-flex flex-column justify-content-between">
    <p><%= deal.name %></p>
    <p class="fs-075r"><%= deal.created_at.strftime("%d %b %Y")%></p>
  </div>

  <p>
    <%= deal.amount %>
  </p>

</div>

app/views/deals/_form.html.erb
<%= form_with(model: [@group, @deal]) do |form| %>
  <% if deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name, class:'form-field', placeholder:'Name' %>

  <%= form.text_field :amount, class:'form-field', placeholder:'Amount' %>

  <%= form.label :categories %>
  <div class='p-2'>
  <% Group.all.each do |category| %>
    <%= check_box_tag "category_ids[]", category.id %>
    <%=h category.name%>
  <% end %>
  </div>

  <div class="category_btn_cnt">
    <%= form.submit 'Add Transaction', class:"category_btn" %>
  </div>
<% end %>

app/views/deals/new.html.erb
<div class="bg-white my-4">
<%= render "form", deal: @deal %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :name, class:'form-field', placeholder:'Name' %>

    <%= form.text_field :icon, class:'form-field', placeholder:'Icon Link' %>

  <div class="category_btn_cnt">
    <%= form.submit 'Create Category', class:"category_btn" %>
  </div>
  
<% end %>

app/views/groups/_group.html.erb
<div class="m-2 bg-white border d-flex justify-content-between p-2" id="<%= dom_id group %>">

  <img src="<%= group.icon%>" alt="<%= group.name%>" class="w-25" >
  <p>
    <%= group.name %>
  </p>

  <p>
    <%= group.expenses %>
  </p>

</div>

app/views/groups/index.html.erb
<h2 class="d-flex justify-content-between px-4 py-4 mb-4 bg-white">
    <span >Total expended: </span>
    <span class="fw-bold text-third">$<%= @total %></span>
</h2>

<div class="container" id="groups">
  <% @groups.includes(:deals).each do |group| %>
    <%= link_to group do %>
    <%= render group %>
    <% end %>
  <% end %>
</div>

<div class="category_btn_cnt">
<%= link_to 'New Category', new_group_path, class:"category_btn" %>
</div>

app/views/groups/new.html.erb
<div class="bg-white my-4">
<%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<h2 class="d-flex justify-content-between px-4 py-4 mb-4 bg-white">
  <span class="">Total on <%= @group.name %>: </span>
  <span class="fw-bold">$<%= @group.expenses %></span>
</h2>

<div class="flex flex-col gap-3 px-4">
  <% @deals.each do |deal| %>
    <%= render deal %>
  <% end %>
</div>

<div class="category_btn_cnt">
<%= link_to 'New Transaction', new_group_deal_path(@group), class:"category_btn" %>
</div>

app/views/layouts/_alert.html.erb
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-blue">
  <div class="d-flex justify-content-around align-items-center w-100 p-2">
    <div class="w-25">
      <% if @previous_path %>
        <%= link_to @previous_path, class: "absolute left-4" do %>
          <img src='https://www.svgrepo.com/show/932/left-arrow.svg' alt='<' class='text-uppercase fs-6 text-white w-25'>
        <% end %>
      <% end %>
    </div>
    <div class=" flex-grow-2">
      <% if @title %>
        <p class="text-uppercase fs-6 m-auto text-white"> <%= @title %> </p>
      <% end %>
    </div>
    <div class="w-25 d-flex justify-content-end">
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "text-uppercase fs-6 text-white p-0 m-0" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "text-uppercase fs-5 text-white" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
 <p class="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "main">
    <%= render 'layouts/navbar'%>
    <%= disp_alerts %>
    <div class="">
    <%= yield %>
    </div>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@600&family=Outfit:wght@100;600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3410ed71d0.js" crossorigin="anonymous"></script>
  </body>
</html>